# https://download.fedoraproject.org/pub/fedora/linux/releases/37/Server/x86_64/iso/Fedora-Server-dvd-x86_64-37-1.7.iso

---
- hosts: localhost
  vars:
    cpus: 8
    memory: 12000
    disk_size: 100000
    packer_output_dir: "{{ ansible_user_dir }}/VMs"
  roles:
    - install-fedora
